/**
  ******************************************************************************
  * @file     lib.c
  * @author   Auto-generated by STM32CubeIDE
  * @version  V1.0
  * @date     20/12/2022 14:52:56
  * @brief    Default under dev library file.
  ******************************************************************************
*/

/* Includes ------------------------------------------------------------------*/
#include "stm32g0xx_hal.h"
#include "string.h"

const char mylongstring[256] = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
int pippo = 32;
int lib_pluto;

/** Functions ----------------------------------------------------------------*/
int __myMul(int a, int b)
{
	return (a * b);
}

__attribute__ ((section (".mysum_sect")))
int __mySum(int a, int b)
{
	lib_pluto++;
	return (a + b);
}

void *myMemcpy (void *__restrict dst, const void *__restrict src, size_t size)
{
	return memcpy(dst, src, size);
}


int getLibPlutoValue (void)
{
	return lib_pluto;
}
